### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by 3vivekb** [amigocloud/python-amigocloud#3]
Any chance you guys want to adapt the package to work with Python 3?

**Comment by alculquicondor** [comment]
addressed in 3fcb362f7eba9cb2d4410321939606fc0638cbcb

**Comment by alculquicondor** [comment]
Hello @3vivekb, we just released v1.2 (also available in pypi). Let me know if you have any issues.

**Comment by 3vivekb** [comment]
Cool i'll try to test it this week.

**Comment by 3vivekb** [comment]
Testing - the python 3 version works great so far.  Installed via pip.
